import Navbar from "@/components/Layouts/Navbar";
import Sidebar from "@/components/Layouts/Sidebar";
import "@/styles/global.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
    return (
        <Suspense fallback={ <p style={{ textAlign: "center" }}>loading... on initial request</p> }>
            <section>
                {children}
            </section>
        </Suspense>
    );
}
